package err

import "errors"

var (
	ERequest              = errors.New("err_request")
	ESign                 = errors.New("err_sign")
	EParam                = errors.New("err_param")
	ECaptcha              = errors.New("err_captcha")
	EUsernameOrPassword   = errors.New("err_username_or_password")
	ERestrictedAdmin      = errors.New("err_restricted_admin")
	EUpload               = errors.New("err_upload")
	ELimitSize            = errors.New("err_limit_size")
	EMIMEType             = errors.New("err_mime_type")
	EInvalidID            = errors.New("err_invalid_id")
	EInvalidName          = errors.New("err_invalid_name")
	ERole                 = errors.New("err_role")
	ERoleNotExists        = errors.New("err_role_not_exists")
	EInvalidRoleName      = errors.New("err_invalid_role_name")
	EGroup                = errors.New("err_group")
	EGroupNotExists       = errors.New("err_group_not_exists")
	EInvalidGroupName     = errors.New("err_invalid_group_name")
	EInvalidAdmin         = errors.New("err_invalid_admin")
	EAdminName            = errors.New("err_admin_name")
	EAdminNameExists      = errors.New("err_admin_name_exists")
	EAdminNameCanNotEmail = errors.New("err_admin_name_can_not_email")
	EMobile               = errors.New("err_mobile")
	EMobileExists         = errors.New("err_mobile_exists")
	EEmail                = errors.New("err_email")
	EEmailExists          = errors.New("err_email_exists")
	EPassword             = errors.New("err_password")
	EConfirmPassword      = errors.New("err_confirm_password")
	EInvalidPID           = errors.New("err_invalid_pid")
	EInvalidRoleID        = errors.New("err_invalid_role_id")
	EInvalidPrivilegeID   = errors.New("err_invalid_privilege_id")
	ECategoryID           = errors.New("err_category_id")
	EWholesalePrice       = errors.New("err_wholesale_price")
	ETitle                = errors.New("err_title")
	ECoverImage           = errors.New("err_cover_image")
	EProductImage         = errors.New("err_product_image")

	EResponse = errors.New("err_response")
)
